steps:
  -   name: 'gcr.io/cloud-builders/git'
      entrypoint: 'bash'
      args: [ '-c', 'git fetch --unshallow --tags && git checkout ${BRANCH_NAME} && git submodule init && git submodule update' ]

  -   name: 'taktik/git-version:2.0.5-g16ba274290'
      args: [ '-f', 'git.version' ]

  -   name: 'docker:24-git'
      entrypoint: 'sh'
      args: [ '-c', 'echo $$REPO_PASSWORD | docker login docker.taktik.be --username=$$REPO_USERNAME --password-stdin' ]
      secretEnv: [ 'REPO_USERNAME', 'REPO_PASSWORD' ]

  -   name: 'docker:24-git'
      entrypoint: 'sh'
      args: ['-c', 'docker buildx create --name multiarch --driver docker-container --use']

  -   name: 'docker:24-git'
      entrypoint: 'sh'
      args: [ '-c', 'docker build --progress=plain -f build.Dockerfile --push -t "docker.taktik.be/icure/icure-kmehr-module:$(cat git.version)" --build-arg "repoUsername=$$REPO_USERNAME" --build-arg "repoPassword=$$REPO_PASSWORD" .' ]
      secretEnv: [ 'REPO_USERNAME', 'REPO_PASSWORD' ]

  -   name: 'docker:24-git'
      entrypoint: 'sh'
      args: [ '-c', 'docker build --builder multiarch --progress=plain -f package.Dockerfile --push --platform linux/amd64,linux/arm64 -t docker.taktik.be/icure/icure-kmehr-module:latest -t docker.taktik.be/icure/icure-kmehr-module:$(cat ./git.version) --build-arg "version=$(cat ./git.version)" .' ]

availableSecrets:
  secretManager:
    - versionName: projects/taktik-dev/secrets/ci-repo-username/versions/1
      env: 'REPO_USERNAME'
    - versionName: projects/taktik-dev/secrets/ci-repo-password/versions/1
      env: 'REPO_PASSWORD'

options:
  pool:
    name: "projects/taktik-dev/locations/europe-west1/workerPools/taktik-gcb-medium-pool"

timeout: 2700s
